@startuml

title Usecase for Information system

actor Арендатор


rectangle Software {

    usecase (Зареєструвати приміщення)
    usecase (Надати показники шуму)
    
    (Надати показники шуму) .> (Зареєструвати приміщення) : include

    Арендатор -- (Надати показники шуму)
    Арендатор -- (Зареєструвати приміщення)
}

@enduml
